### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by wussup** [bluejamesbond/TextJustify-Android#106]
Hello, I have this error. My DocumentView is part of LinearLayout without any ListViews, but LinearLayout is part of ScrollView. Please, help.

`java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
	at com.bluejamesbond.text.DocumentView$CacheBitmap.&lt;init&gt;(DocumentView.java:809)
	at com.bluejamesbond.text.DocumentView.allocateResources(DocumentView.java:636)
	at com.bluejamesbond.text.DocumentView.onMeasure(DocumentView.java:477)
	at android.view.View.measure(View.java:17495)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:17495)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
	at android.view.View.measure(View.java:17495)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
	at android.view.View.measure(View.java:17495)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1779)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.widget.ScrollView.onMeasure(ScrollView.java:476)
	at android.view.View.measure(View.java:17495)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
	at android.view.View.measure(View.java:17495)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
	at android.view.View.measure(View.java:17495)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:17495)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:17495)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
	at android.view.View.measure(View.java:17495)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2285)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1396)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1595)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6637)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
	at android.view.Choreographer.doCallbacks(Choreographer.java:614)
	at android.view.Choreographer.doFrame(Choreographer.java:584)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by Hivanshu** [comment]
Any Solutions till yet facing same problem ??? Please help

**Comment by wussup** [comment]
Probably new version of TextJustify helped me.

**Comment by Hivanshu** [comment]
Using the Latest Version 2.1.6. Problem i have faced in this version.

**Comment by Hivanshu** [comment]
Error Message

java.lang.OutOfMemoryError: Failed to allocate a 9676812 byte allocation with 7341528 free bytes and 7MB until OOM

Where

DocumentView.java:809

Short Stacktrace
0 	java.lang.OutOfMemoryError: Failed to allocate a 9676812 byte allocation with 7341528 free bytes and 7MB until OOM
1 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
2 	at android.graphics.Bitmap.nativeCreate(Native Method)
3 	at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
4 	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
5 	at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
6 	at com.bluejamesbond.text.DocumentView$CacheBitmap.<init>(DocumentView.java:809)
7 	at com.bluejamesbond.text.DocumentView.allocateResources(DocumentView.java:636)
8 	at com.bluejamesbond.text.DocumentView.onMeasure(DocumentView.java:477)
9 	at android.view.View.measure(View.java:20151)
10 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
11 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
12 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
13 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
14 	at android.view.View.measure(View.java:20151)
15 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2104)
16 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
17 	at android.widget.ScrollView.onMeasure(ScrollView.java:510)
18 	at android.view.View.measure(View.java:20151)
19 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
20 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
21 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
22 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
23 	at android.view.View.measure(View.java:20151)
24 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
25 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
26 	at android.view.View.measure(View.java:20151)
27 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
28 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
29 	at android.view.View.measure(View.java:20151)
30 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
31 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:669)
32 	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:736)
33 	at android.view.View.measure(View.java:20151)
34 	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1079)
35 	at android.view.View.measure(View.java:20151)
36 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
37 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
38 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
39 	at android.view.View.measure(View.java:20151)
40 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
41 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
42 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
43 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
44 	at android.view.View.measure(View.java:20151)
45 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
46 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
47 	at android.view.View.measure(View.java:20151)
48 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
49 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
50 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
51 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
52 	at android.view.View.measure(View.java:20151)
53 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
54 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
55 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3158)
56 	at android.view.View.measure(View.java:20151)
57 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2594)
58 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
59 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
60 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
61 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
62 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
63 	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
64 	at android.view.Choreographer.doFrame(Choreographer.java:631)
65 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
66 	at android.os.Handler.handleCallback(Handler.java:739)
67 	at android.os.Handler.dispatchMessage(Handler.java:95)
68 	at android.os.Looper.loop(Looper.java:158)
69 	at android.app.ActivityThread.main(ActivityThread.java:7224)
70 	at java.lang.reflect.Method.invoke(Native Method)
71 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
72 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by bitkill** [comment]
Same problem here. Latest version of TextJustify (2.1.6)

**Comment by bluejamesbond** [comment]
Try to disable caching for this `ext:documentView_cacheConfig="no_cache"`

**Comment by bitkill** [comment]
Thanks. That helped a lot,
